### ISSUE TITLE
STB - Playing channel in VLC

### ISSUE THREAD

**Issue by skamene** [ozankaraali/QiTV#4] opened 2024-07-03 04:37 UTC
Hello Ozan,

Firstly, thank you for taking the time to develop this application. Good, open-source STB players are non-existent.  

I just updated to version 1.4.4 and had a little glitch while trying to play a channel in VLC vs the built-in player.  Here are my steps to reproduce the issue:

1) Select the channel in the channel list - the channel starts playing in the built-in player
2) Hit Stop - the channel stops playing
3) Hit "Open in VLC" - VLC open, the name appears in the VLC playlist as "3609?play_token=XbZKkowWWT"
4) Immediately get an error message from VLC that says "VLC is not able to open the MRL http://example-stb:80/f9qqQNouqv/4gXiszLvdp/3609?play_token= XbZKkowWWT

I used Wireshark to capture the process of starting to play the channel using the built-in player.  I know you know all this but I just wanted to document this for my own understanding as well.

The player sends this request to the STB server  

http://example-stb:80/server/load.php?type=itv&action=create_link&type=itv&cmd=ffmpeg http://localhost/ch/3609_&JsHttpRequest=1-xml

the STB server comes back with a URL that looks similar to this:

{"js":{"id":"3609","cmd":"ffmpeg http://example-stb:80/f9qqQNouqv/4gXiszLvdp/3609?play_token= XbZKkowWWT"},"streamer_id":0,"link_id":0,"load":0,"error":""}

Then the client issues another GET to play the stream

http://example-stb:80/f9qqQNouqv/4gXiszLvdp/3609?play_token=XbZKkowWWT

the STB server returns with Status 302 and the header contains a new key and value.

Key: Location
Value: http://random_ip_here:27556/f9qqQNouqv/4gXiszLvdp/3609?play_token=XbZKkowWWT&token=OXhFWWt3TjNPTXdmRUp3

 Interestingly enough it's no longer the http://example-stb but a random IP address.  I suppose they are trying to hide the original location, not sure.
Finally, the last GET is to this new location and it starts playing fine in the built-in player. I tried to manually open the new location in VLC but got the same error message about VLC cannot open the location.
Any thoughts ?

Thank you so much for trying to help.

**Comment by ozankaraali** [comment] 2024-07-03 05:38
Hi @skamene ,
Thanks for detailed explanation. Can you try to get the url, but not play with built-in player? I guess you can modify the app from source, try to log the new url but don’t pass it to the player and try to play returned url. I suspect that when you play somewhere once, it consumes that token provided after 302, which is kinda weird because if so, how the stream will recover from a buffer issue and stuff? But basically built-in player is the same as VLC player under the hood. Interesting, try that and we can talk.

**Comment by skamene** [comment] 2024-07-03 14:56
Hello Ozan,

Thank you for the quick reply.  I am a junior Python scripter,  and modifying your code is way above my skill set  :) . I am on a Mac, installed qt using brew, cloned your repo and tried to run main.py and it immediately complained about missing qdarktheme module.  So that's where I am at.   Would like to help and learn along the way but crippled by my inexperience.

**Comment by ozankaraali** [comment] 2024-07-03 14:58
Use python 3.8 or disable qtdarktheme

**Comment by skamene** [comment] 2024-07-03 15:14
Thank you sir, making a little progress. I have Python 3.9.7.  Had to install pyside6, URLObject and orjson.  I am now able to run "python main.py" and the app comes up.

So you are suggesting I add a print statement to video_player.py,  specifically to function play_video and see what the video_url looks like and try to open in an external VLC player?

Thank you again for your guidance, this is fun.

**Comment by ozankaraali** [comment] 2024-07-03 15:16
right, also do not pass the media player instance so it won’t consume the link

**Comment by skamene** [comment] 2024-07-03 15:25
ok, just tried that. The URL looks like this:

http://example-stb:80/f9qqQNouqv/4gXiszLvdp/2878?play_token=x8J1HpBeqy

I open VLC on my Mac, select to open Network location, paste the URL and hit open. Immediately get the error about not able to open the MRL.  Very puzzling.

**Comment by ozankaraali** [comment] 2024-07-03 15:27
Weird, I cannot say anthing further without reproducing the issue myself. Under the hood, the player of QiTV is VLC already.

**Comment by skamene** [comment] 2024-07-03 15:32
Ozan,

May I reach out to you via other  means (X, Telegram) ?

Thank you

**Comment by ozankaraali** [comment] 2024-07-03 15:33
Sure, I may not be able to answer instantly but OzanKaraali is my handle, or ozan_karaali

**Comment by skamene** [comment] 2024-07-03 15:34
that's no worries, this is not urgent.  Are those handles on X or Telegram?

**Comment by ozankaraali** [comment] 2024-07-03 15:35
OzanKaraali is on telegram, the other is Twitter

**Comment by ozankaraali** [comment] 2024-07-03 18:37
I am closing the issue since it is not a bug of QiTV as we diagnosed.

**Closed by ozankaraali** 2024-07-03 18:37 UTC
